export const rawBrandTokens = {
  color: {
    ivory: "#F6F1EA",
    warmCream: "#EFE7D9",
    softWhite: "#FBF8F3",
    sand: "#DCCBAE",
    sage: "#A2AC95",
    deepForest: "#2F3E34",
    copper: "#C47A4A",
    charcoal: "#4F4A43",
    taupe: "#C8B7A3",
    white: "#FFFFFF",
  },
  typography: {
    fontFamily: {
      display: '"Playfair Display", Georgia, "Times New Roman", serif',
      body: 'Inter, "Segoe UI", Arial, sans-serif',
    },
    fontWeight: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    fontSize: {
      xs: "0.75rem",
      sm: "0.875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "2rem",
      "4xl": "3rem",
    },
    lineHeight: {
      tight: 1.1,
      snug: 1.25,
      normal: 1.5,
      relaxed: 1.65,
    },
    letterSpacing: {
      tight: "-0.02em",
      normal: "0",
      wide: "0.08em",
    },
  },
  spacing: {
    0: "0",
    1: "0.25rem",
    2: "0.5rem",
    3: "0.75rem",
    4: "1rem",
    5: "1.25rem",
    6: "1.5rem",
    8: "2rem",
    10: "2.5rem",
    12: "3rem",
    16: "4rem",
    20: "5rem",
    24: "6rem",
  },
  radius: {
    none: "0",
    sm: "0.5rem",
    md: "0.75rem",
    lg: "1rem",
    xl: "1.5rem",
    pill: "9999px",
  },
  shadow: {
    none: "none",
    sm: "0 8px 24px rgba(79, 74, 67, 0.08)",
    md: "0 16px 40px rgba(79, 74, 67, 0.12)",
    lg: "0 24px 60px rgba(47, 62, 52, 0.16)",
  },
  breakpoint: {
    sm: "40rem",
    md: "48rem",
    lg: "64rem",
    xl: "80rem",
    "2xl": "96rem",
  },
  zIndex: {
    base: 0,
    raised: 10,
    sticky: 100,
    overlay: 400,
    modal: 500,
    toast: 600,
    tooltip: 700,
  },
} as const;

export const designTokens = {
  color: {
    background: {
      base: rawBrandTokens.color.ivory,
      soft: rawBrandTokens.color.warmCream,
      sage: rawBrandTokens.color.sage,
      deepGreen: rawBrandTokens.color.deepForest,
    },
    surface: {
      card: rawBrandTokens.color.softWhite,
      elevated: rawBrandTokens.color.white,
    },
    text: {
      primary: rawBrandTokens.color.charcoal,
      secondary: "#6A645D",
      muted: "#8A837A",
      inverse: rawBrandTokens.color.white,
    },
    brand: {
      copper: rawBrandTokens.color.copper,
      green: rawBrandTokens.color.deepForest,
    },
    cta: {
      primary: rawBrandTokens.color.deepForest,
      primaryHover: "#243129",
      secondary: rawBrandTokens.color.warmCream,
    },
    border: {
      subtle: rawBrandTokens.color.taupe,
      strong: "#8B8174",
    },
    status: {
      success: "#4B6B4F",
      warning: "#A56A2A",
      danger: "#A1463C",
      info: "#5D7A7A",
    },
  },
  typography: {
    fontFamily: rawBrandTokens.typography.fontFamily,
    fontWeight: rawBrandTokens.typography.fontWeight,
    fontSize: rawBrandTokens.typography.fontSize,
    lineHeight: rawBrandTokens.typography.lineHeight,
    letterSpacing: rawBrandTokens.typography.letterSpacing,
  },
  spacing: rawBrandTokens.spacing,
  radius: rawBrandTokens.radius,
  shadow: rawBrandTokens.shadow,
  breakpoint: rawBrandTokens.breakpoint,
  zIndex: rawBrandTokens.zIndex,
} as const;

export type DesignTokens = typeof designTokens;
