import { RoleKey } from "./roles";
import { PERMISSION_KEYS, type PermissionKey } from "./permissions";

const PARENT_PERMISSIONS = [
  PERMISSION_KEYS.APP_ACCESS,
  PERMISSION_KEYS.FAMILY_SELF,
  PERMISSION_KEYS.MARKETPLACE_SELF,
  PERMISSION_KEYS.EVENTS_SELF,
  PERMISSION_KEYS.REPORTS_SELF,
  PERMISSION_KEYS.SAVED_SELF,
  PERMISSION_KEYS.NOTIFICATIONS_SELF,
] as const satisfies readonly PermissionKey[];

const SELLER_PERMISSIONS = [
  ...PARENT_PERMISSIONS,
  PERMISSION_KEYS.LISTINGS_OWN_MANAGE,
] as const satisfies readonly PermissionKey[];

const ORGANIZER_PERMISSIONS = [
  ...PARENT_PERMISSIONS,
  PERMISSION_KEYS.EVENTS_OWN_MANAGE,
] as const satisfies readonly PermissionKey[];

const MODERATOR_PERMISSIONS = [
  PERMISSION_KEYS.ADMIN_ACCESS,
  PERMISSION_KEYS.REPORTS_MODERATE,
  PERMISSION_KEYS.CONTENT_MODERATE,
] as const satisfies readonly PermissionKey[];

const ADMIN_PERMISSIONS = [
  ...MODERATOR_PERMISSIONS,
  PERMISSION_KEYS.USERS_MANAGE,
  PERMISSION_KEYS.ADMIN_MANAGE,
  PERMISSION_KEYS.AUDIT_READ,
] as const satisfies readonly PermissionKey[];

const SUPER_ADMIN_PERMISSIONS = [
  ...ADMIN_PERMISSIONS,
  PERMISSION_KEYS.ROLES_MANAGE,
  PERMISSION_KEYS.SETTINGS_MANAGE,
] as const satisfies readonly PermissionKey[];

const EMPTY_PERMISSIONS = [] as const satisfies readonly PermissionKey[];

export const rolePermissions = {
  [RoleKey.PARENT]: PARENT_PERMISSIONS,
  [RoleKey.SELLER]: SELLER_PERMISSIONS,
  [RoleKey.ORGANIZER]: ORGANIZER_PERMISSIONS,
  [RoleKey.EXPERT]: EMPTY_PERMISSIONS,
  [RoleKey.PARTNER]: EMPTY_PERMISSIONS,
  [RoleKey.MUNICIPALITY_USER]: EMPTY_PERMISSIONS,
  [RoleKey.MODERATOR]: MODERATOR_PERMISSIONS,
  [RoleKey.ADMIN]: ADMIN_PERMISSIONS,
  [RoleKey.SUPER_ADMIN]: SUPER_ADMIN_PERMISSIONS,
  [RoleKey.SYSTEM]: EMPTY_PERMISSIONS,
} as const satisfies Record<RoleKey, readonly PermissionKey[]>;
